package com.properties.crud.data;

import com.properties.crud.model.Property;

/**
 * PropertyData is the same as Property but with id
 * This is to ensure the Property saved is with id
 * And the id is uniquely generated by the application
 */
public class PropertyData extends Property {
    private int id;

    public PropertyData(Property property, Integer id){
        this.id = id;
        this.setAddress(property.getAddress());
        this.setNoOfBedrooms(property.getNoOfBedrooms());
        this.setSizeBySqrFoot(property.getSizeBySqrFoot());
        this.setPurchasePrice(property.getPurchasePrice());
    }

    public int getId() {
        return id;
    }

    public void copy(Property property){
        this.setAddress(property.getAddress());
        this.setNoOfBedrooms(property.getNoOfBedrooms());
        this.setSizeBySqrFoot(property.getSizeBySqrFoot());
        this.setPurchasePrice(property.getPurchasePrice());
    }
}
